title: Massage Gun Rack Docs
description: Documentation for the Massage Gun Rack project.
theme: just-the-docs

url: https://yourcomputer-com.github.io/docs.mgrack.com/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
