title: Massage Gun Rack
description: Documentation for the Massage Gun Rack project.
theme: just-the-docs

url: https://docs.mgrack.com/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

defaults:
  - scope:
      path: "content"
    values:
      permalink: /:basename/
